### ISSUE TITLE
Is this a typo ?

### ISSUE THREAD

**Issue by duffo64** [ScruffR/VL53L0X#1]
Should value be uint32_t ?

// Read a 32-bit register
uint32_t VL53L0X::readReg32Bit(uint8_t reg)
{
<b>uint16_t value;</b>

  return value;
}

**Comment by ScruffR** [comment]
Probably - good catch :+1:

I'll correct that on here and forward that issue to the original Pololu repo.

**Comment by ScruffR** [comment]
I've corrected that, but I see there are more of these errors all over the original lib.
I'll have to start correcting them bit by bit - but I'll close this one.
